<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class RealEmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        Employee::truncate();
        User::whereIn('role', ['admin', 'teacher', 'employee'])->delete();

        $employees = [
            // KEPALA SEKOLAH & MANAJEMEN
            [
                'employee_code' => 'KS001',
                'first_name' => 'Drs.',
                'last_name' => 'I Nyoman Suardika',
                'email' => 'kepala.sekolah@smp-saraswati.sch.id',
                'phone' => '+62361234567',
                'address' => 'Jl. Kamboja No. 11, Denpasar',
                'date_of_birth' => '1970-05-15',
                'gender' => 'male',
                'position' => 'Kepala Sekolah',
                'department' => 'Manajemen',
                'hire_date' => '2010-07-01',
                'employment_type' => 'full-time',
                'salary' => 15000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'admin',
            ],
            [
                'employee_code' => 'WK001',
                'first_name' => 'Dra.',
                'last_name' => 'Ni Ketut Suartini, M.Pd',
                'email' => 'wakil.kepala@smp-saraswati.sch.id',
                'phone' => '+62361234568',
                'address' => 'Jl. Teratai No. 22, Denpasar',
                'date_of_birth' => '1972-08-20',
                'gender' => 'female',
                'position' => 'Wakil Kepala Sekolah',
                'department' => 'Manajemen',
                'hire_date' => '2012-01-15',
                'employment_type' => 'full-time',
                'salary' => 12000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'admin',
            ],

            // GURU MATEMATIKA
            [
                'employee_code' => 'GM001',
                'first_name' => 'I Made',
                'last_name' => 'Suryawan, S.Pd',
                'email' => 'made.suryawan@smp-saraswati.sch.id',
                'phone' => '+62361234569',
                'address' => 'Jl. Melati No. 5, Denpasar',
                'date_of_birth' => '1985-03-12',
                'gender' => 'male',
                'position' => 'Guru Matematika',
                'department' => 'Matematika & IPA',
                'hire_date' => '2015-07-20',
                'employment_type' => 'full-time',
                'salary' => 7000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],
            [
                'employee_code' => 'GM002',
                'first_name' => 'Ni Luh',
                'last_name' => 'Komang Ayu, S.Pd',
                'email' => 'luh.komang@smp-saraswati.sch.id',
                'phone' => '+62361234570',
                'address' => 'Jl. Anggrek No. 8, Denpasar',
                'date_of_birth' => '1988-11-25',
                'gender' => 'female',
                'position' => 'Guru Matematika',
                'department' => 'Matematika & IPA',
                'hire_date' => '2016-08-01',
                'employment_type' => 'full-time',
                'salary' => 6500000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU BAHASA INDONESIA
            [
                'employee_code' => 'GBI001',
                'first_name' => 'I Ketut',
                'last_name' => 'Wiradana, S.Pd',
                'email' => 'ketut.wiradana@smp-saraswati.sch.id',
                'phone' => '+62361234571',
                'address' => 'Jl. Mawar No. 12, Denpasar',
                'date_of_birth' => '1983-07-08',
                'gender' => 'male',
                'position' => 'Guru Bahasa Indonesia',
                'department' => 'Bahasa',
                'hire_date' => '2014-01-10',
                'employment_type' => 'full-time',
                'salary' => 6800000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],
            [
                'employee_code' => 'GBI002',
                'first_name' => 'Ni Putu',
                'last_name' => 'Surya Dewi, S.Pd',
                'email' => 'putu.surya@smp-saraswati.sch.id',
                'phone' => '+62361234572',
                'address' => 'Jl. Dahlia No. 3, Denpasar',
                'date_of_birth' => '1990-02-14',
                'gender' => 'female',
                'position' => 'Guru Bahasa Indonesia',
                'department' => 'Bahasa',
                'hire_date' => '2017-07-15',
                'employment_type' => 'full-time',
                'salary' => 6500000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU BAHASA INGGRIS
            [
                'employee_code' => 'GBG001',
                'first_name' => 'I Wayan',
                'last_name' => 'Adi Putra, S.Pd',
                'email' => 'wayan.adi@smp-saraswati.sch.id',
                'phone' => '+62361234573',
                'address' => 'Jl. Cempaka No. 7, Denpasar',
                'date_of_birth' => '1986-09-20',
                'gender' => 'male',
                'position' => 'Guru Bahasa Inggris',
                'department' => 'Bahasa',
                'hire_date' => '2015-08-01',
                'employment_type' => 'full-time',
                'salary' => 7200000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],
            [
                'employee_code' => 'GBG002',
                'first_name' => 'Ni Made',
                'last_name' => 'Ratna Sari, S.Pd',
                'email' => 'made.ratna@smp-saraswati.sch.id',
                'phone' => '+62361234574',
                'address' => 'Jl. Kenanga No. 15, Denpasar',
                'date_of_birth' => '1989-12-05',
                'gender' => 'female',
                'position' => 'Guru Bahasa Inggris',
                'department' => 'Bahasa',
                'hire_date' => '2016-07-20',
                'employment_type' => 'full-time',
                'salary' => 6800000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU IPA
            [
                'employee_code' => 'GIPA001',
                'first_name' => 'I Komang',
                'last_name' => 'Gede Supartha, S.Si',
                'email' => 'komang.gede@smp-saraswati.sch.id',
                'phone' => '+62361234575',
                'address' => 'Jl. Tulip No. 9, Denpasar',
                'date_of_birth' => '1984-06-18',
                'gender' => 'male',
                'position' => 'Guru IPA',
                'department' => 'Matematika & IPA',
                'hire_date' => '2014-07-15',
                'employment_type' => 'full-time',
                'salary' => 7000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],
            [
                'employee_code' => 'GIPA002',
                'first_name' => 'Ni Kadek',
                'last_name' => 'Suartini, S.Si',
                'email' => 'kadek.suartini@smp-saraswati.sch.id',
                'phone' => '+62361234576',
                'address' => 'Jl. Sakura No. 6, Denpasar',
                'date_of_birth' => '1987-04-22',
                'gender' => 'female',
                'position' => 'Guru IPA',
                'department' => 'Matematika & IPA',
                'hire_date' => '2015-08-10',
                'employment_type' => 'full-time',
                'salary' => 6800000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU IPS
            [
                'employee_code' => 'GIPS001',
                'first_name' => 'I Nyoman',
                'last_name' => 'Suwitra, S.Pd',
                'email' => 'nyoman.suwitra@smp-saraswati.sch.id',
                'phone' => '+62361234577',
                'address' => 'Jl. Lotus No. 11, Denpasar',
                'date_of_birth' => '1982-10-30',
                'gender' => 'male',
                'position' => 'Guru IPS',
                'department' => 'IPS',
                'hire_date' => '2013-07-15',
                'employment_type' => 'full-time',
                'salary' => 6900000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],
            [
                'employee_code' => 'GIPS002',
                'first_name' => 'Ni Nengah',
                'last_name' => 'Sukarini, S.Pd',
                'email' => 'nengah.sukarini@smp-saraswati.sch.id',
                'phone' => '+62361234578',
                'address' => 'Jl. Flamboyan No. 4, Denpasar',
                'date_of_birth' => '1986-01-17',
                'gender' => 'female',
                'position' => 'Guru IPS',
                'department' => 'IPS',
                'hire_date' => '2014-08-01',
                'employment_type' => 'full-time',
                'salary' => 6700000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU PENDIDIKAN AGAMA HINDU
            [
                'employee_code' => 'GPH001',
                'first_name' => 'Ida Bagus',
                'last_name' => 'Putu Arta, S.Ag',
                'email' => 'bagus.putu@smp-saraswati.sch.id',
                'phone' => '+62361234579',
                'address' => 'Jl. Bougenvil No. 13, Denpasar',
                'date_of_birth' => '1980-03-25',
                'gender' => 'male',
                'position' => 'Guru Pendidikan Agama Hindu',
                'department' => 'Agama & PKN',
                'hire_date' => '2012-01-10',
                'employment_type' => 'full-time',
                'salary' => 7000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU PENJASORKES
            [
                'employee_code' => 'GPJ001',
                'first_name' => 'I Gede',
                'last_name' => 'Mahendra, S.Pd',
                'email' => 'gede.mahendra@smp-saraswati.sch.id',
                'phone' => '+62361234580',
                'address' => 'Jl. Kamboja No. 18, Denpasar',
                'date_of_birth' => '1988-07-12',
                'gender' => 'male',
                'position' => 'Guru Penjasorkes',
                'department' => 'Olahraga & Seni',
                'hire_date' => '2016-07-15',
                'employment_type' => 'full-time',
                'salary' => 6500000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU SENI BUDAYA
            [
                'employee_code' => 'GSB001',
                'first_name' => 'Ni Luh',
                'last_name' => 'Putu Arini, S.Sn',
                'email' => 'luh.arini@smp-saraswati.sch.id',
                'phone' => '+62361234581',
                'address' => 'Jl. Jepun No. 20, Denpasar',
                'date_of_birth' => '1991-05-08',
                'gender' => 'female',
                'position' => 'Guru Seni Budaya',
                'department' => 'Olahraga & Seni',
                'hire_date' => '2018-07-20',
                'employment_type' => 'full-time',
                'salary' => 6000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU PKN
            [
                'employee_code' => 'GPKN001',
                'first_name' => 'I Made',
                'last_name' => 'Rai Sutawan, S.Pd',
                'email' => 'made.rai@smp-saraswati.sch.id',
                'phone' => '+62361234582',
                'address' => 'Jl. Pandan No. 14, Denpasar',
                'date_of_birth' => '1983-11-28',
                'gender' => 'male',
                'position' => 'Guru PKN',
                'department' => 'Agama & PKN',
                'hire_date' => '2014-01-15',
                'employment_type' => 'full-time',
                'salary' => 6700000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // GURU TIK
            [
                'employee_code' => 'GTIK001',
                'first_name' => 'I Putu',
                'last_name' => 'Gede Ariawan, S.Kom',
                'email' => 'putu.gede@smp-saraswati.sch.id',
                'phone' => '+62361234583',
                'address' => 'Jl. Bougenville No. 16, Denpasar',
                'date_of_birth' => '1990-08-15',
                'gender' => 'male',
                'position' => 'Guru TIK',
                'department' => 'Teknologi',
                'hire_date' => '2017-07-20',
                'employment_type' => 'full-time',
                'salary' => 6500000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'teacher',
            ],

            // STAFF TATA USAHA (TU)
            [
                'employee_code' => 'TU001',
                'first_name' => 'I Wayan',
                'last_name' => 'Sudiarta',
                'email' => 'wayan.sudiarta@smp-saraswati.sch.id',
                'phone' => '+62361234584',
                'address' => 'Jl. Raya Sesetan No. 25, Denpasar',
                'date_of_birth' => '1978-02-10',
                'gender' => 'male',
                'position' => 'Kepala Tata Usaha',
                'department' => 'Administrasi',
                'hire_date' => '2011-01-05',
                'employment_type' => 'full-time',
                'salary' => 8000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],
            [
                'employee_code' => 'TU002',
                'first_name' => 'Ni Ketut',
                'last_name' => 'Sukerti',
                'email' => 'ketut.sukerti@smp-saraswati.sch.id',
                'phone' => '+62361234585',
                'address' => 'Jl. Gatot Subroto No. 8, Denpasar',
                'date_of_birth' => '1985-06-20',
                'gender' => 'female',
                'position' => 'Staff TU - Administrasi',
                'department' => 'Administrasi',
                'hire_date' => '2013-07-15',
                'employment_type' => 'full-time',
                'salary' => 5000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],
            [
                'employee_code' => 'TU003',
                'first_name' => 'I Made',
                'last_name' => 'Suwena',
                'email' => 'made.suwena@smp-saraswati.sch.id',
                'phone' => '+62361234586',
                'address' => 'Jl. Hayam Wuruk No. 12, Denpasar',
                'date_of_birth' => '1987-09-14',
                'gender' => 'male',
                'position' => 'Staff TU - Keuangan',
                'department' => 'Administrasi',
                'hire_date' => '2014-08-01',
                'employment_type' => 'full-time',
                'salary' => 5200000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],
            [
                'employee_code' => 'TU004',
                'first_name' => 'Ni Putu',
                'last_name' => 'Ayu Lestari',
                'email' => 'putu.lestari@smp-saraswati.sch.id',
                'phone' => '+62361234587',
                'address' => 'Jl. Veteran No. 5, Denpasar',
                'date_of_birth' => '1992-04-18',
                'gender' => 'female',
                'position' => 'Staff TU - Kepegawaian',
                'department' => 'Administrasi',
                'hire_date' => '2018-01-10',
                'employment_type' => 'full-time',
                'salary' => 4800000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],

            // STAFF PERPUSTAKAAN
            [
                'employee_code' => 'PUS001',
                'first_name' => 'Ni Made',
                'last_name' => 'Sri Wahyuni',
                'email' => 'made.sri@smp-saraswati.sch.id',
                'phone' => '+62361234588',
                'address' => 'Jl. Cokroaminoto No. 7, Denpasar',
                'date_of_birth' => '1986-12-22',
                'gender' => 'female',
                'position' => 'Pustakawan',
                'department' => 'Perpustakaan',
                'hire_date' => '2015-07-15',
                'employment_type' => 'full-time',
                'salary' => 4500000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],

            // LABORAN
            [
                'employee_code' => 'LAB001',
                'first_name' => 'I Komang',
                'last_name' => 'Agus Wira',
                'email' => 'komang.agus@smp-saraswati.sch.id',
                'phone' => '+62361234589',
                'address' => 'Jl. Tukad Yeh Aya No. 9, Denpasar',
                'date_of_birth' => '1989-07-30',
                'gender' => 'male',
                'position' => 'Laboran IPA',
                'department' => 'Laboratorium',
                'hire_date' => '2016-08-01',
                'employment_type' => 'full-time',
                'salary' => 4000000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],

            // PENJAGA SEKOLAH & CLEANING SERVICE
            [
                'employee_code' => 'CS001',
                'first_name' => 'I Wayan',
                'last_name' => 'Suamba',
                'email' => 'wayan.suamba@smp-saraswati.sch.id',
                'phone' => '+62361234590',
                'address' => 'Jl. Nakula No. 3, Denpasar',
                'date_of_birth' => '1975-03-05',
                'gender' => 'male',
                'position' => 'Penjaga Sekolah',
                'department' => 'Umum',
                'hire_date' => '2010-01-10',
                'employment_type' => 'full-time',
                'salary' => 3500000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],
            [
                'employee_code' => 'CS002',
                'first_name' => 'Ni Nyoman',
                'last_name' => 'Suartini',
                'email' => 'nyoman.suartini@smp-saraswati.sch.id',
                'phone' => '+62361234591',
                'address' => 'Jl. Sahadewa No. 11, Denpasar',
                'date_of_birth' => '1980-08-12',
                'gender' => 'female',
                'position' => 'Cleaning Service',
                'department' => 'Umum',
                'hire_date' => '2012-02-15',
                'employment_type' => 'full-time',
                'salary' => 3200000.00,
                'salary_type' => 'monthly',
                'status' => 'active',
                'role' => 'employee',
            ],

            // PEGAWAI CUTI
            [
                'employee_code' => 'GM003',
                'first_name' => 'Ni Kadek',
                'last_name' => 'Dwi Anjani, S.Pd',
                'email' => 'kadek.dwi@smp-saraswati.sch.id',
                'phone' => '+62361234592',
                'address' => 'Jl. Nakula No. 17, Denpasar',
                'date_of_birth' => '1990-06-10',
                'gender' => 'female',
                'position' => 'Guru Matematika',
                'department' => 'Matematika & IPA',
                'hire_date' => '2017-07-15',
                'employment_type' => 'full-time',
                'salary' => 6500000.00,
                'salary_type' => 'monthly',
                'status' => 'on_leave',
                'role' => 'teacher',
            ],
        ];

        foreach ($employees as $employeeData) {
            // Create user first
            $role = $employeeData['role'];
            unset($employeeData['role']);

            $user = User::create([
                'name' => $employeeData['first_name'].' '.$employeeData['last_name'],
                'email' => $employeeData['email'],
                'password' => Hash::make('password123'),
                'role' => $role,
            ]);

            // Create employee
            $employeeData['user_id'] = $user->id;
            $employeeData['emergency_contact'] = json_encode([
                'name' => 'Emergency Contact',
                'phone' => '+6281234567890',
                'relation' => 'Family',
            ]);

            Employee::create($employeeData);
        }

        $this->command->info('✅ Created '.count($employees).' real employees for SMP Saraswati Denpasar');
        $this->command->info('📊 Statistics:');
        $this->command->info('   - Admin/Manajemen: '.User::where('role', 'admin')->count());
        $this->command->info('   - Teachers (Guru): '.User::where('role', 'teacher')->count());
        $this->command->info('   - Staff: '.User::where('role', 'employee')->count());
        $this->command->info('   - Active: '.Employee::where('status', 'active')->count());
        $this->command->info('   - On Leave: '.Employee::where('status', 'on_leave')->count());
    }
}
