export interface ValidationResult {
  isValid: boolean;
  errors: string[];
}

/**
 * Validate row for SIMPLIFIED import (4 columns only)
 * Required fields: full_name, email, hire_date, role
 * Employee code and password will be auto-generated by backend
 */
export function validateRow(row: any): ValidationResult {
  const errors: string[] = [];

  // Check if this is simplified format (4 columns)
  const isSimplified = 'full_name' in row && !('employee_code' in row && 'first_name' in row);

  if (isSimplified) {
    // SIMPLIFIED FORMAT VALIDATION (4 columns)

    // Required: full_name
    if (!row.full_name?.trim()) {
      errors.push('Nama lengkap wajib diisi');
    }

    // Required: email
    if (!row.email?.trim()) {
      errors.push('Email wajib diisi');
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(row.email)) {
      errors.push('Format email tidak valid');
    }

    // Required: hire_date
    if (!row.hire_date?.trim()) {
      errors.push('Tanggal masuk wajib diisi');
    } else if (!/^\d{4}-\d{2}-\d{2}$/.test(row.hire_date)) {
      errors.push('Tanggal masuk harus format YYYY-MM-DD (contoh: 2024-01-15)');
    }

    // Required: role
    if (!row.role?.trim()) {
      errors.push('Role wajib diisi');
    } else if (!['admin', 'teacher', 'employee'].includes(row.role.toLowerCase())) {
      errors.push('Role harus: admin, teacher, atau employee');
    }
  } else {
    // LEGACY FORMAT VALIDATION (17 columns) - for backward compatibility

    if (!row.employee_code?.trim()) errors.push('Employee code is required');
    if (!row.first_name?.trim()) errors.push('First name is required');
    if (!row.last_name?.trim()) errors.push('Last name is required');
    if (!row.email?.trim()) errors.push('Email is required');
    if (!row.hire_date?.trim()) errors.push('Hire date is required');

    // Email format
    if (row.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(row.email)) {
      errors.push('Invalid email format');
    }

    // Date format for hire_date
    if (row.hire_date && !/^\d{4}-\d{2}-\d{2}$/.test(row.hire_date)) {
      errors.push('Hire date must be in format YYYY-MM-DD');
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
  };
}